apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookingwiz-admin
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookingwiz-admin
  template:
    metadata:
      labels:
        app: bookingwiz-admin
    spec:
      containers:
        - name: bookingwiz-admin
          image: bookingwizacr.azurecr.io/bookingwiz-admin:latest  # Ensure tag is updated in CI/CD
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bookingwiz-admin-svc
  namespace: production
spec:
  selector:
    app: bookingwiz-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP  # Keep backend internal
