apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookingwiz-web
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookingwiz-web
  template:
    metadata:
      labels:
        app: bookingwiz-web
    spec:
      containers:
      - name: bookingwiz-web
        image: bookingwizacr.azurecr.io/bookingwiz-web:latest  # Use 'latest' or dynamically update it
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: bookingwiz-web-svc
  namespace: staging
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: bookingwiz-web
  type: LoadBalancer
