apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookingwiz-admin
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookingwiz-admin
  template:
    metadata:
      labels:
        app: bookingwiz-admin
    spec:
      containers:
      - name: bookingwiz-admin
        image: bookingwizacr.azurecr.io/bookingwiz-admin:latest  # Use 'latest' or dynamically update it
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health  # Make sure this endpoint exists in your API
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: bookingwiz-admin-svc
  namespace: staging
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: bookingwiz-admin
  type: LoadBalancer
