name: PR Check

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Node.js environment for React frontend (v18 for React 18.3.1)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies for BookingWiz_Web (React frontend)
      - name: Install Frontend Dependencies
        working-directory: ./BookingWiz_Web
        run: |
          npm install
          npm install react-router-dom

      # Build BookingWiz_Web, bypassing ESLint warnings in CI
      - name: Build Frontend
        working-directory: ./BookingWiz_Web
        run: CI=false npm run build  # Prevents ESLint warnings from failing the build

      # Run frontend tests if they exist
      - name: Test Frontend
        working-directory: ./BookingWiz_Web
        run: npm test --if-present  # Skips if no tests are defined

      # Setup .NET SDK for BookingWiz_Admin (v8.0)
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Restore dependencies for .NET backend
      - name: Restore Backend Dependencies
        working-directory: ./BookingWiz_Admin
        run: dotnet restore

      # Build BookingWiz_Admin in Release configuration
      - name: Build Backend
        working-directory: ./BookingWiz_Admin
        run: dotnet build --configuration Release

      # Run backend tests, proceeding even if no tests exist
      - name: Test Backend
        working-directory: ./BookingWiz_Admin
        run: dotnet test --no-restore --verbosity normal
        continue-on-error: true  # Allows pipeline to continue if tests fail or are absent
